### ISSUE TITLE
Error on basic example

### ISSUE THREAD

**Issue by yudao** [stapl-dsl/stapl-core#2]
Hi,

I'm interested about XACML like with Scala.

I'm trying to reproduce your basic test, and just with the compilation of the ExamplePolicy object I have an error:

``` scala
sbt run
[info] Loading global plugins from /Users/xxxxx/.sbt/0.13/plugins
[info] Loading project definition from /Users/xxxxx/Documents/workspace/minimal-scala/project
[info] Set current project to minimal-scala (in build file:/Users/xxxxx/Documents/workspace/minimal-scala/)
[info] Compiling 1 Scala source to /Users/xxxxx/Documents/workspace/minimal-scala/target/scala-2.11/classes...
[error] /Users/xxxxx/Documents/workspace/minimal-scala/src/main/scala/com/example/ExamplePolicy.scala:12: overloaded method value := with alternatives:
[error]   (effectKeyword: stapl.core.dsl.EffectKeyword)stapl.core.Rule <and>
[error]   (t: stapl.core.dsl.EffectAndObligationActions)stapl.core.Rule <and>
[error]   (t: stapl.core.dsl.EffectAndCondition)stapl.core.Rule <and>
[error]   (t: stapl.core.dsl.EffectConditionAndObligationActions)stapl.core.Rule
[error]  cannot be applied to (stapl.core.dsl.OnlyTarget)
[error]     Rule("permit physicians") := when ("physician" in subject.roles) permit,
[error]                               ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 4 s, completed 6 oct. 2015 13:30:03
```

Regards,

Yu.

**Comment by yudao** [comment]
I've changed the type of method because in the error I've posted before we can see there are no signature with stapl.core.dsl.OnlyTarget type.

So I changed with stapl.core.dsl.EffectAndCondition and now I'm getting no exists error on attribute role.

This is my gist => https://gist.github.com/yudao/e45cfb682a8bde6cfe6f

So, why this error? because I've defined the subject roles attribute in my evaluate parameters and my policy.

Thx,

Yu.

**Comment by yudao** [comment]
Ok! Sorry I'm not importing in my Hello.scala file

``` scala
import com.example.ExamplePolicy.subject
```

But i'm aware to know why you don't want to have a stapl.core.dsl.OnlyTarget type signature (my first post) like your example in the ReadMe, I find this more DSListic :)

Thx.

Yu.

**Comment by maartendecat** [comment]
Hi Yu,

So am I correct that adding the import fixed the problem for you?

With regard to the OnlyTarget signature: this is semantically equivalent with specifying a condition, but no target, in your case:

```
Rule("permit physicians") := permit iff ("physician" in subject.roles)
```

We chose to opt for this form and chose not to support the other in order to avoid confusion. Moreover, the target of a Rule actually is useless, you can always combine this with the condition and get exactly the same results. Because of that, we were actually thinking of deprecating the target for Rules and only keeping it for Policies where it actually makes sense.

Does that answer your question?

Kind regards,

Maarten

**Comment by yudao** [comment]
@maartendecat Yes, thx a lot. It's a great library, go on folks! ;)
